# Generated by Django 5.1.5 on 2025-09-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_address_alter_customer_phone"),
        ("customers", "0003_backfill_customers"),
    ]

    operations = []
