# Generated by Django 5.1.7 on 2025-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordereditem",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
