# Generated by Django 5.1.7 on 2025-04-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_ordereditem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
