# Generated by Django 5.1.7 on 2025-04-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordereditem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
